// Code generated by go-genconstructor; DO NOT EDIT.

package application

func NewOperatorDescriptor(
	id string,
	typ string,
) OperatorDescriptor {
	return OperatorDescriptor{
		id:  id,
		typ: typ,
	}
}
